/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "(Android) Version number": {                    "en": "(Android) Version number",                        "de": "(Android) Versions Nummer"},
    "Adapter Timeout (in ms)": {                     "en": "Adapter Timeout (in ms)",                         "de": "Adapter Timeout (in ms)"},
    "Adapter timeout": {                             "en": "Adapter timeout",                                 "de": "Adapter Timeout"},
    "Complete URL of the Ryd backend server": {      "en": "Complete URL of the Ryd backend server",          "de": "Komplette URL des Ryd Backend Servers"},
    "Country code of the Ryd Android App": {         "en": "Country code of the Ryd Android App",             "de": "L&auml;nder Code der Ryd Android App"},
    "Device OS version": {                           "en": "Device OS version",                               "de": "Device OS Version"},
    "Device Resolution": {                           "en": "Device Resolution",                               "de": "Device Aufl&ouml;sung"},
    "Device type": {                                 "en": "Device type",                                     "de": "Device Typ"},
    "Device type which is running the Ryd App": {    "en": "Device type which is running the Ryd App",        "de": "Device Typ auf der die Ryd App l&auml;uft"},
    "Email": {                                       "en": "Email",                                           "de": "Email"},
    "Email of your Ryd account": {                   "en": "Email of your Ryd account",                       "de": "Email deines Ryd Accounts"},
    "Ignore the following think (car) properties (comma seperated)": {"en": "Ignore the following think (car) properties (comma seperated)", "de": "Die folgenden Eigenschaften werden nicht angezeigt (Komma getrennt)"},
    "Internal (Android) device ID which is running the Ryd App": {"en": "Internal (Android) device ID which is running the Ryd App", "de": "Interne (Android) Device ID auf der die Ryd App l&auml;uft"},
    "Internal device ID": {                          "en": "Internal device ID",                              "de": "Interne Device ID"},
    "Internal name of the Ryd Android App": {        "en": "Internal name of the Ryd Android App",            "de": "Interner Name der Ryd Android App"},
    "Internal settings": {                           "en": "Internal settings",                               "de": "Interne Einstellungen"},
    "Parse the following think (car) properties (comma seperated)": {"en": "Parse the following think (car) properties (comma seperated)", "de": "Die folgenden Eigenschaften werden analysiert (Komma getrennt)"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort"},
    "Password of your Ryd account": {                "en": "Password of your Ryd account",                    "de": "Passwort deines Ryd Accounts"},
    "Resolution of the client device": {             "en": "Resolution of the client device",                 "de": "Aufl&ouml;sung des Client Ger&auml;tes"},
    "Ryd App internal name": {                       "en": "Ryd App internal name",                           "de": "Ryd App Interner Name"},
    "Ryd App locale": {                              "en": "Ryd App locale",                                  "de": "Ryd App Locale"},
    "Ryd App version": {                             "en": "Ryd App version",                                 "de": "Ryd App Version"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen"},
    "Think properties": {                            "en": "Think properties",                                "de": "Think Eigenschaften"},
    "Think properties (ignore)": {                   "en": "Think properties (ignore)",                       "de": "Think Eigenschaften (Ignorieren)"},
    "URL Ryd server": {                              "en": "URL Ryd server",                                  "de": "URL des Ryd Servers"},
    "Version number of the Ryd Android App": {       "en": "Version number of the Ryd Android App",           "de": "Versions Nummer der Ryd Android App"},
    "internal_note": {                               "en": "Please don't change anything on this page unless you know what you're doing.", "de": "Bitte nichts auf dieser Seite ändern, außer Du weißt was du tust."},
};